#!/bin/bash
##########################################################################################################
# This script is used to install BaseInfra powered by SS.
# usage:
#   ./installSS.sh masterIP node1IP node2IP ...
#
# Prerequisites:
#   OS: centos 7.2 +  
#   ssh enabled
#   Has the root user, and the password must be iso*help (You need modify the script manually if not)
#   Only for BaseInfra84#
# 
# Date: 12/29/2016
##########################################################################################################
masterIP=$1

InfraPack=HPESW_ITOM_Suite_Platform_2017.01.00100
infraBuildUrl=ftp://shcitomctfs.hpeswlab.net/Builds/for_itsma/${InfraPack}.zip

function usage() {
	echo usage:
	echo   ./installSS.sh masterIP node1IP node2IP ...
	exit
}

function prepareInfraInstallPackage() {
	echo "Prepare infra installer package for $1...."
	rm -rf ${InfraPack}.zip ${InfraPack}
	nohup ssh root@$1 'wget --user=cmfshare --password=cmfshare ftp://shcitomctfs.hpeswlab.net/Builds/latest/HPESW_ITOM_Suite_Platform_2017.01.00100.zip && unzip HPESW_ITOM_Suite_Platform_2017.01.00100.zip' > /dev/null &
}

function installK8sNode() {
	nodeIP=$1
	echo "Installing infro on node ${nodeIP}..."

	rm -rf ssl
	ssh root@${nodeIP} 'rm -rf ssl'

	mkdir ssl && cp /opt/kubernetes/ssl/* ssl/ && tar czv ssl | ssh root@${nodeIP} 'tar xz'

	tar czv ${InfraPack}/install.properties | ssh root@${nodeIP} 'tar xz'

	ssh root@${nodeIP} 'sed -i "s#^CLIENT_CA_FILE=.*#CLIENT_CA_FILE=/root/ssl/ca.crt#" HPESW_ITOM_Suite_Platform_2017.01.00100/install.properties'
	ssh root@${nodeIP} 'sed -i "s#^CLIENT_CERT_FILE=.*#CLIENT_CERT_FILE=/root/ssl/client.crt#" HPESW_ITOM_Suite_Platform_2017.01.00100/install.properties'
	ssh root@${nodeIP} 'sed -i "s#^CLIENT_KEY_FILE=.*#CLIENT_KEY_FILE=/root/ssl/client.key#" HPESW_ITOM_Suite_Platform_2017.01.00100/install.properties'

	# sync the system time between node and master, or pod itsma-installer might not be created successfully.
	ssh root@${nodeIP} "date --set \"$(date)\""

	ssh root@${nodeIP} 'nohup ./HPESW_ITOM_Suite_Platform_2017.01.00100/install &' &
}

# arguments check
if [[ -z $@ ]]
then
	usage
fi

# prepare ssh public key login
rm -f /root/.ssh/id_rsa*

yes y | ssh-keygen -f /root/.ssh/id_rsa -N ''

# push the public key to nodes
cat << EOF > /root/sshPass.sh
#!/bin/bash
echo \$PASSWORD
EOF

chmod 777 /root/sshPass.sh

export SSH_ASKPASS=/root/sshPass.sh
export DISPLAY=:0
for nodeIP in ${@:2}
do
	PASSWORD=iso*help setsid ssh-copy-id -o StrictHostKeyChecking=no root@${nodeIP}
done

rm -f /root/sshPass.sh

# download infra build on every node in parallel
for nodeIP in ${@:2}
do
	prepareInfraInstallPackage ${nodeIP}
done

# download infra build on master
wget --user=cmfshare --password=cmfshare ${infraBuildUrl} && unzip ${InfraPack}.zip

hostname=$(hostname -f)
if [[ -z ${hostname} ]]
then
	echo "Error! Hostname can not be empty."
	exit 1
fi

workerNodes=${@:2}
echo "workerNodes: ${workerNodes}"

sed -i "s#^MASTER_NODES=.*#MASTER_NODES=\"${masterIP}\"#" ${InfraPack}/install.properties
sed -i "s#^WORKER_NODES=.*#WORKER_NODES=\"${workerNodes}\"#" ${InfraPack}/install.properties
sed -i "s#^INGRESS_IP=.*#INGRESS_IP=${masterIP}#" ${InfraPack}/install.properties
sed -i "s#^EXTERNAL_ACCESS_HOST=.*#EXTERNAL_ACCESS_HOST=${hostname}#" ${InfraPack}/install.properties
sed -i "s#^NFS_SERVER_IP=.*#NFS_SERVER_IP=${masterIP}#" ${InfraPack}/install.properties

# setupNFS on master
./${InfraPack}/scripts/setupNFS.sh

# install BaseInfra on master
./${InfraPack}/install

# grant read access to all user, files in ssl/ will be needed for nodes
chmod a+r /opt/kubernetes/ssl/*

sleep 10s

for nodeIP in ${@:2}
do
	installK8sNode ${nodeIP}
done

groupadd -g 1999 itsma
useradd -g 1999 -u 1999 itsma

# wait until all installations finish
wait

kubectl get nodes

echo "The base infra has been installed successfully."
